/* 
 * Copyright 2014 Institute fml (TU Munich) and Institute FLW (TU Dortmund).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package kodemat.PA;

import com.hazelcast.core.IMap;
import flw.energieeffizienz.FLW_EEATelegramSyncedTable;
import kodemat.tele.test.TelegramField;
import kodemat.versioning.visuHistory.VisuComponentInfoEntry;
import kodemat.visu.swing.tables.EHBTelegramSyncedTable;
import kodemat.visudata.VisuHelper;

/**
 *
 * @author Kipouridis
 */
public class HandoverManagerWindow extends javax.swing.JFrame {
    private  VisuHelper visuHelper=null;
    private IMap<Integer, TelegramField> telegramsMap;


    /**
     * Creates new form HandoverManager
     */
    public HandoverManagerWindow() {
        initComponents();
    }

   public HandoverManagerWindow(VisuHelper helper) {
       
       this.visuHelper = helper;
       telegramsMap = visuHelper.getTelegrams();

        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        flwAufgestelltLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        abgabeZyclusLabel = new javax.swing.JLabel();
        fördererAnfrageLabel = new javax.swing.JLabel();
        wartenLabel = new javax.swing.JLabel();
        step7 = new javax.swing.JLabel();
        step6 = new javax.swing.JLabel();
        ehbFahrtLabel1 = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("FLW Anlage");
        jLabel10.setToolTipText("");
        jLabel10.setOpaque(true);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 260, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("fml Anlage");
        jLabel11.setToolTipText("");
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 270, 40));

        jLabel12.setBackground(new java.awt.Color(192, 192, 192));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fahrt in Bearbeitungsstation");
        jLabel12.setToolTipText("");
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 240, 40));

        flwAufgestelltLabel.setBackground(new java.awt.Color(192, 192, 192));
        flwAufgestelltLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        flwAufgestelltLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flwAufgestelltLabel.setText("Behälter aufgestellt");
        flwAufgestelltLabel.setToolTipText("");
        flwAufgestelltLabel.setOpaque(true);
        flwAufgestelltLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flwAufgestelltLabelMouseClicked(evt);
            }
        });
        jPanel3.add(flwAufgestelltLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 260, 40));

        jLabel14.setBackground(new java.awt.Color(192, 192, 192));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Stapelfeigabe aufehoben");
        jLabel14.setToolTipText("");
        jLabel14.setAutoscrolls(true);
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 250, 40));

        abgabeZyclusLabel.setBackground(new java.awt.Color(192, 192, 192));
        abgabeZyclusLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        abgabeZyclusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abgabeZyclusLabel.setText("Übergabe Anfrage");
        abgabeZyclusLabel.setToolTipText("");
        abgabeZyclusLabel.setOpaque(true);
        abgabeZyclusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abgabeZyclusLabelMouseClicked(evt);
            }
        });
        jPanel3.add(abgabeZyclusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 260, 40));

        fördererAnfrageLabel.setBackground(new java.awt.Color(192, 192, 192));
        fördererAnfrageLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fördererAnfrageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fördererAnfrageLabel.setText("Warte auf Behälter Ankunft ");
        fördererAnfrageLabel.setToolTipText("");
        fördererAnfrageLabel.setOpaque(true);
        fördererAnfrageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fördererAnfrageLabelMouseClicked(evt);
            }
        });
        jPanel3.add(fördererAnfrageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 260, 40));

        wartenLabel.setBackground(new java.awt.Color(192, 192, 192));
        wartenLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wartenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wartenLabel.setText("Warten");
        wartenLabel.setToolTipText("");
        wartenLabel.setOpaque(true);
        jPanel3.add(wartenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 260, 40));

        step7.setBackground(new java.awt.Color(192, 192, 192));
        step7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        step7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        step7.setText("Übergabe beendet");
        step7.setToolTipText("");
        step7.setOpaque(true);
        step7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                step7MouseClicked(evt);
            }
        });
        jPanel3.add(step7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 240, 40));

        step6.setBackground(new java.awt.Color(192, 192, 192));
        step6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        step6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        step6.setText("Beginne Übergabe");
        step6.setToolTipText("");
        step6.setOpaque(true);
        step6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                step6MouseClicked(evt);
            }
        });
        jPanel3.add(step6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 240, 40));

        ehbFahrtLabel1.setBackground(new java.awt.Color(192, 192, 192));
        ehbFahrtLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ehbFahrtLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ehbFahrtLabel1.setText("Fahrt in Übergabestation No3");
        ehbFahrtLabel1.setToolTipText("");
        ehbFahrtLabel1.setOpaque(true);
        ehbFahrtLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ehbFahrtLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(ehbFahrtLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 260, 40));

        testButton.setText("test step 6");
        testButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testButtonMouseClicked(evt);
            }
        });
        jPanel3.add(testButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, -1, -1));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab1", jPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fördererAnfrageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fördererAnfrageLabelMouseClicked
        
          EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Behälter_angekommen_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");

    }//GEN-LAST:event_fördererAnfrageLabelMouseClicked

    private void flwAufgestelltLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flwAufgestelltLabelMouseClicked
        EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Behälter_aufgestellt_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");
         
    }//GEN-LAST:event_flwAufgestelltLabelMouseClicked

    private void ehbFahrtLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ehbFahrtLabel1MouseClicked
    FLW_EEATelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new FLW_EEATelegramSyncedTable(this.visuHelper.getHazelcastMap("Transportauftrag_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");

    }//GEN-LAST:event_ehbFahrtLabel1MouseClicked

    private void abgabeZyclusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abgabeZyclusLabelMouseClicked
         EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Uebergabeanfrage_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");

    }//GEN-LAST:event_abgabeZyclusLabelMouseClicked

    private void step6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_step6MouseClicked
         EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Beginne_Uebergabe_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");

    }//GEN-LAST:event_step6MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
         EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Uebergabe_Beendet_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void step7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_step7MouseClicked
        // TODO add your handling code here:
         EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("Uebergabe_Beendet_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");
    }//GEN-LAST:event_step7MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
         EHBTelegramSyncedTable<VisuComponentInfoEntry, VisuComponentInfoEntry> telegramEditor = new EHBTelegramSyncedTable(this.visuHelper.getHazelcastMap("EHB_nach_Bearbeitungsstation_telegram"), this.visuHelper, VisuComponentInfoEntry.class, "EHB Order Editor");
    }//GEN-LAST:event_jLabel12MouseClicked

    private void testButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testButtonMouseClicked
        // TODO this button is only to test, to set the finalized to true for step 6:
        
        this.visuHelper.getHazelcastMap(telegramsMap.get(6).getValue()).put(25, new VisuComponentInfoEntry(25, "finalized", "true"));
        
        
    }//GEN-LAST:event_testButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandoverManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandoverManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandoverManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandoverManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HandoverManagerWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abgabeZyclusLabel;
    private javax.swing.JLabel ehbFahrtLabel1;
    private javax.swing.JLabel flwAufgestelltLabel;
    private javax.swing.JLabel fördererAnfrageLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel step6;
    private javax.swing.JLabel step7;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel wartenLabel;
    // End of variables declaration//GEN-END:variables

 
}
